### ISSUE TITLE
Allow rationals for typefaces and colours

### ISSUE THREAD

**Issue by thomasjbradley** [thomasjbradley/patternbot#15]
Maybe add more YAML into the main readme, something like:

```yml
type:
  primary: |
    This typeface should be used for blah, blah
colors:
  primary: |
    The primary colours should be used for blah, blah
```
