### ISSUE TITLE
Allow Patternbot colours & fonts to be customized

### ISSUE THREAD

**Issue by thomasjbradley** [thomasjbradley/patternbot#66]
The look of the pattern library itself should match the brand.

Some customization ideas:

- `navColour`
- `primaryFont`
- `secondaryFont`
- `linkColour` or just use one of the primary/secondary colours

**Comment by thomasjbradley** [comment]
Should all this be added under a `customize` entry in the `README.md`?

```yml
customize:
  backgroundColour: ""
  navColour: ""
```
